<?php

/**
 * Baseproject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $cnp_id
 * @property string $basecamp_id
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getCnpId()       Returns the current record's "cnp_id" value
 * @method string  getBasecampId()  Returns the current record's "basecamp_id" value
 * @method project setId()          Sets the current record's "id" value
 * @method project setName()        Sets the current record's "name" value
 * @method project setCnpId()       Sets the current record's "cnp_id" value
 * @method project setBasecampId()  Sets the current record's "basecamp_id" value
 * 
 * @package    basecamp2cnp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseproject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cnp_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('basecamp_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}