<?php

/**
 * Basetimelog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $cnp_id
 * @property string $basecamp_id
 * @property date $date
 * @property text $description
 * @property integer $hours
 * @property integer $person_id
 * @property integer $project_id
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method string  getName()        Returns the current record's "name" value
 * @method string  getCnpId()       Returns the current record's "cnp_id" value
 * @method string  getBasecampId()  Returns the current record's "basecamp_id" value
 * @method date    getDate()        Returns the current record's "date" value
 * @method text    getDescription() Returns the current record's "description" value
 * @method integer getHours()       Returns the current record's "hours" value
 * @method integer getPersonId()    Returns the current record's "person_id" value
 * @method integer getProjectId()   Returns the current record's "project_id" value
 * @method timelog setId()          Sets the current record's "id" value
 * @method timelog setName()        Sets the current record's "name" value
 * @method timelog setCnpId()       Sets the current record's "cnp_id" value
 * @method timelog setBasecampId()  Sets the current record's "basecamp_id" value
 * @method timelog setDate()        Sets the current record's "date" value
 * @method timelog setDescription() Sets the current record's "description" value
 * @method timelog setHours()       Sets the current record's "hours" value
 * @method timelog setPersonId()    Sets the current record's "person_id" value
 * @method timelog setProjectId()   Sets the current record's "project_id" value
 * 
 * @package    basecamp2cnp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basetimelog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('timelog');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cnp_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('basecamp_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('hours', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('person_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('project_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}