<?php

/**
 * BaseioTimeLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $cnp_id
 * @property string $basecamp_id
 * 
 * @method string    getName()        Returns the current record's "name" value
 * @method string    getCnpId()       Returns the current record's "cnp_id" value
 * @method string    getBasecampId()  Returns the current record's "basecamp_id" value
 * @method ioTimeLog setName()        Sets the current record's "name" value
 * @method ioTimeLog setCnpId()       Sets the current record's "cnp_id" value
 * @method ioTimeLog setBasecampId()  Sets the current record's "basecamp_id" value
 * 
 * @package    basecamp2cnp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseioTimeLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('io_time_log');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cnp_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('basecamp_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}