<?php

/**
 * ioPersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ioPersonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ioPersonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ioPerson');
    }
}