<?php

/**
 * ioProjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ioProjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ioProjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ioProject');
    }
}