<?php

/**
 * ioTimeLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ioTimeLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ioTimeLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ioTimeLog');
    }
}