<?php

/**
 * person
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    basecamp2cnp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class person extends Baseperson
{
  public function setFirstName($str)
  {
    $this->_set('first_name', $str);
    $this->name = sprintf('%s %s', $str, $this->getLastName());
  }
  
  public function setLastName($str)
  {
    $this->_set('last_name', $str);
    $this->name = sprintf('%s %s', $this->getFirstName(), $str);
  }
}
