<?php

/**
 * personTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class personTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object personTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('person');
    }
}