<?php

/**
 * timeEntry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    basecamp2cnp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class timeEntry extends BasetimeEntry
{
  public function getPersonDbId()
  {
    $object = Doctrine::getTable('person')->findOneByBasecampId($this->getPersonId());
    
    if (!$object)
    {
      return 0;
    }
    
    return $object->getId();
  }

  public function getProjectDbId()
  {
    $object = Doctrine::getTable('project')->findOneByBasecampId($this->getProjectId());
    
    if (!$object)
    {
      return 0;
    }
    
    return $object->getId();
  }
}
