generator:
  class: sfDoctrineGenerator
  param:
    model_class:           timeentry
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          timeentry
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [date, description, hours, person, project]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
